- name: Install docker
  hosts: all
  become: yes
  vars_files:
    - env_variables

  tasks:
    - name: Install system required packages
      apt: name={{ item }} state=present update_cache=yes force_apt_get=yes
      loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'gnupg' ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg 
        state: present

    - name: Add the stable Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

    - name: Install Docker CE
      apt: name=docker-ce update_cache=yes state=latest

    - name: Add your limited Linux user account to the docker group
      shell: "usermod -aG docker $USER" 
